// 지하철 역 목록과 노선 색상 데이터를 제공한다.
export type StationDto = {
    name: string
    lines: string[]
    description: string
}

export const lineColors: Record<string, string> = {
    "1": "#0052A4",
    "2": "#00A84D",
    "3": "#EF7C1C",
    "4": "#00A5DE",
    "5": "#996CAC",
    "6": "#CD7C2F",
    "7": "#747F00",
    "8": "#E6186C",
    "9": "#BDB092",
    "경의중앙": "#77C4A3",
    "공항": "#0090D2",
    "경춘": "#0C8E72",
    "경강": "#003DA5",
    "신분당": "#D4003B",
    "수인분당": "#FABE00",
    "우이신설": "#B7C452",
    "서해": "#8FC31F",
    "신림": "#6789CA",
    "김포골드": "#A17800",
    "GTX-A": "#9A6292",
    "인천1": "#7CA8D5",
    "인천2": "#ED8B00",
    "의정부": "#FDA600",
    "용인": "#56AA1C",
}

export const stations: StationDto[] = [
    { name: "4·19민주묘지", lines: ["우이신설"], description: "" },
    { name: "가능", lines: ["1"], description: "" },
    { name: "가락시장", lines: ["3", "8"], description: "환승역" },
    { name: "가산디지털단지", lines: ["1", "7"], description: "환승역" },
    { name: "가양", lines: ["9"], description: "" },
    { name: "가오리", lines: ["우이신설"], description: "" },
    { name: "가재울", lines: ["인천2"], description: "" },
    { name: "가정", lines: ["인천2"], description: "" },
    { name: "가정중앙시장", lines: ["인천2"], description: "" },
    { name: "가좌", lines: ["경의중앙"], description: "" },
    { name: "가천대", lines: ["수인분당"], description: "" },
    { name: "가평", lines: ["경춘"], description: "" },
    { name: "간석", lines: ["1"], description: "" },
    { name: "간석오거리", lines: ["인천1"], description: "" },
    { name: "갈매", lines: ["경춘"], description: "" },
    { name: "갈산", lines: ["인천1"], description: "" },
    { name: "강남", lines: ["2", "신분당"], description: "환승역" },
    { name: "강남구청", lines: ["7", "수인분당"], description: "환승역" },
    { name: "강남대", lines: ["용인"], description: "" },
    { name: "강동", lines: ["5"], description: "" },
    { name: "강동구청", lines: ["8"], description: "" },
    { name: "강매", lines: ["경의중앙"], description: "" },
    { name: "강변", lines: ["2"], description: "" },
    { name: "강일", lines: ["5"], description: "" },
    { name: "강촌", lines: ["경춘"], description: "" },
    { name: "개롱", lines: ["5"], description: "" },
    { name: "개봉", lines: ["1"], description: "" },
    { name: "개포동", lines: ["수인분당"], description: "" },
    { name: "개화", lines: ["9"], description: "" },
    { name: "개화산", lines: ["5"], description: "" },
    { name: "거여", lines: ["5"], description: "" },
    { name: "건대입구", lines: ["2", "7"], description: "환승역" },
    { name: "걸포북변", lines: ["김포골드"], description: "" },
    { name: "검단사거리", lines: ["인천2"], description: "" },
    { name: "검단오류", lines: ["인천2"], description: "" },
    { name: "검단호수공원", lines: ["인천1"], description: "" },
    { name: "검바위", lines: ["인천2"], description: "" },
    { name: "검암", lines: ["공항", "인천2"], description: "환승역" },
    { name: "경기광주", lines: ["경강"], description: "" },
    { name: "경기도청북부청사", lines: ["의정부"], description: "" },
    { name: "경마공원", lines: ["4"], description: "" },
    { name: "경복궁", lines: ["3"], description: "" },
    { name: "경인교대입구", lines: ["인천1"], description: "" },
    { name: "경전철의정부", lines: ["의정부"], description: "" },
    { name: "경찰병원", lines: ["3"], description: "" },
    { name: "계산", lines: ["인천1"], description: "" },
    { name: "계양", lines: ["공항", "인천1"], description: "환승역" },
    { name: "고덕", lines: ["5"], description: "" },
    { name: "고려대", lines: ["6"], description: "" },
    { name: "고색", lines: ["수인분당"], description: "" },
    { name: "고속터미널", lines: ["3", "7", "9"], description: "환승역" },
    { name: "고잔", lines: ["4", "수인분당"], description: "환승역" },
    { name: "고진", lines: ["용인"], description: "" },
    { name: "고촌", lines: ["김포골드"], description: "" },
    { name: "곡산", lines: ["경의중앙", "서해"], description: "환승역" },
    { name: "곤제", lines: ["의정부"], description: "" },
    { name: "곤지암", lines: ["경강"], description: "" },
    { name: "공덕", lines: ["5", "6", "경의중앙", "공항"], description: "환승역" },
    { name: "공릉", lines: ["7"], description: "" },
    { name: "공항시장", lines: ["9"], description: "" },
    { name: "공항화물청사", lines: ["공항"], description: "" },
    { name: "과천", lines: ["4"], description: "" },
    { name: "관악", lines: ["1"], description: "" },
    { name: "관악산", lines: ["신림"], description: "" },
    { name: "광교", lines: ["신분당"], description: "" },
    { name: "광교중앙", lines: ["신분당"], description: "" },
    { name: "광나루", lines: ["5"], description: "" },
    { name: "광명", lines: ["1"], description: "" },
    { name: "광명사거리", lines: ["7"], description: "" },
    { name: "광운대", lines: ["1", "경춘"], description: "환승역" },
    { name: "광화문", lines: ["5"], description: "" },
    { name: "광흥창", lines: ["6"], description: "" },
    { name: "교대", lines: ["2", "3"], description: "환승역" },
    { name: "구래", lines: ["김포골드"], description: "" },
    { name: "구로", lines: ["1"], description: "" },
    { name: "구로디지털단지", lines: ["2"], description: "" },
    { name: "구룡", lines: ["수인분당"], description: "" },
    { name: "구리", lines: ["8", "경의중앙"], description: "환승역" },
    { name: "구반포", lines: ["9"], description: "" },
    { name: "구산", lines: ["6"], description: "" },
    { name: "구성", lines: ["수인분당", "GTX-A"], description: "환승역" },
    { name: "구의", lines: ["2"], description: "" },
    { name: "구일", lines: ["1"], description: "" },
    { name: "구파발", lines: ["3"], description: "" },
    { name: "국수", lines: ["경의중앙"], description: "" },
    { name: "국제업무지구", lines: ["인천1"], description: "" },
    { name: "국회의사당", lines: ["9"], description: "" },
    { name: "군자", lines: ["5", "7"], description: "환승역" },
    { name: "군포", lines: ["1"], description: "" },
    { name: "굴봉산", lines: ["경춘"], description: "" },
    { name: "굴포천", lines: ["7"], description: "" },
    { name: "굽은다리", lines: ["5"], description: "" },
    { name: "귤현", lines: ["인천1"], description: "" },
    { name: "금곡", lines: ["경춘"], description: "" },
    { name: "금릉", lines: ["경의중앙"], description: "" },
    { name: "금정", lines: ["1", "4"], description: "환승역" },
    { name: "금천구청", lines: ["1"], description: "" },
    { name: "금촌", lines: ["경의중앙"], description: "" },
    { name: "금호", lines: ["3"], description: "" },
    { name: "기흥", lines: ["수인분당", "용인"], description: "환승역" },
    { name: "길동", lines: ["5"], description: "" },
    { name: "길음", lines: ["4"], description: "" },
    { name: "김량장", lines: ["용인"], description: "" },
    { name: "김유정", lines: ["경춘"], description: "" },
    { name: "김포공항", lines: ["5", "9", "공항", "서해", "김포골드"], description: "환승역" },
    { name: "까치산", lines: ["2", "5"], description: "환승역" },
    { name: "까치울", lines: ["7"], description: "" },
    { name: "낙성대", lines: ["2"], description: "" },
    { name: "남구로", lines: ["7"], description: "" },
    { name: "남동구청", lines: ["인천2"], description: "" },
    { name: "남동인더스파크", lines: ["수인분당"], description: "" },
    { name: "남부터미널", lines: ["3"], description: "" },
    { name: "남성", lines: ["7"], description: "" },
    { name: "남영", lines: ["1"], description: "" },
    { name: "남위례", lines: ["8"], description: "" },
    { name: "남춘천", lines: ["경춘"], description: "" },
    { name: "남태령", lines: ["4"], description: "" },
    { name: "남한산성입구", lines: ["8"], description: "" },
    { name: "내방", lines: ["7"], description: "" },
    { name: "노들", lines: ["9"], description: "" },
    { name: "노량진", lines: ["1", "9"], description: "환승역" },
    { name: "노원", lines: ["4", "7"], description: "환승역" },
    { name: "녹번", lines: ["3"], description: "" },
    { name: "녹사평", lines: ["6"], description: "" },
    { name: "녹양", lines: ["1"], description: "" },
    { name: "녹천", lines: ["1"], description: "" },
    { name: "논현", lines: ["7", "신분당"], description: "환승역" },
    { name: "능곡", lines: ["경의중앙", "서해"], description: "환승역" },
    { name: "다산", lines: ["8"], description: "" },
    { name: "단대오거리", lines: ["8"], description: "" },
    { name: "달미", lines: ["서해"], description: "" },
    { name: "달월", lines: ["수인분당"], description: "" },
    { name: "답십리", lines: ["5"], description: "" },
    { name: "당곡", lines: ["신림"], description: "" },
    { name: "당산", lines: ["2", "9"], description: "환승역" },
    { name: "당정", lines: ["1"], description: "" },
    { name: "대곡", lines: ["3", "경의중앙", "서해", "GTX-A"], description: "환승역" },
    { name: "대공원", lines: ["4"], description: "" },
    { name: "대림", lines: ["2", "7"], description: "환승역" },
    { name: "대모산입구", lines: ["수인분당"], description: "" },
    { name: "대방", lines: ["1", "신림"], description: "환승역" },
    { name: "대성리", lines: ["경춘"], description: "" },
    { name: "대야미", lines: ["4"], description: "" },
    { name: "대청", lines: ["3"], description: "" },
    { name: "대치", lines: ["3"], description: "" },
    { name: "대화", lines: ["3"], description: "" },
    { name: "대흥", lines: ["6"], description: "" },
    { name: "덕계", lines: ["1"], description: "" },
    { name: "덕소", lines: ["경의중앙"], description: "" },
    { name: "덕정", lines: ["1"], description: "" },
    { name: "도곡", lines: ["3", "수인분당"], description: "환승역" },
    { name: "도농", lines: ["경의중앙"], description: "" },
    { name: "도림천", lines: ["2"], description: "" },
    { name: "도봉", lines: ["1"], description: "" },
    { name: "도봉산", lines: ["1", "7"], description: "환승역" },
    { name: "도심", lines: ["경의중앙"], description: "" },
    { name: "도원", lines: ["1"], description: "" },
    { name: "도화", lines: ["1"], description: "" },
    { name: "독립문", lines: ["3"], description: "" },
    { name: "독바위", lines: ["6"], description: "" },
    { name: "독산", lines: ["1"], description: "" },
    { name: "독정", lines: ["인천2"], description: "" },
    { name: "돌곶이", lines: ["6"], description: "" },
    { name: "동구릉", lines: ["8"], description: "" },
    { name: "동대문", lines: ["1", "4"], description: "환승역" },
    { name: "동대문역사문화공원", lines: ["2", "4", "5"], description: "환승역" },
    { name: "동대입구", lines: ["3"], description: "" },
    { name: "동두천", lines: ["1"], description: "" },
    { name: "동두천중앙", lines: ["1"], description: "" },
    { name: "동막", lines: ["인천1"], description: "" },
    { name: "동묘앞", lines: ["1", "6"], description: "환승역" },
    { name: "동백", lines: ["용인"], description: "" },
    { name: "동수", lines: ["인천1"], description: "" },
    { name: "동암", lines: ["1"], description: "" },
    { name: "동오", lines: ["의정부"], description: "" },
    { name: "동인천", lines: ["1"], description: "" },
    { name: "동작", lines: ["4", "9"], description: "환승역" },
    { name: "동천", lines: ["신분당"], description: "" },
    { name: "동춘", lines: ["인천1"], description: "" },
    { name: "동탄", lines: ["GTX-A"], description: "" },
    { name: "두정", lines: ["1"], description: "" },
    { name: "둔전", lines: ["용인"], description: "" },
    { name: "둔촌동", lines: ["5"], description: "" },
    { name: "둔촌오륜", lines: ["9"], description: "" },
    { name: "등촌", lines: ["9"], description: "" },
    { name: "디지털미디어시티", lines: ["6", "경의중앙", "공항"], description: "환승역" },
    { name: "뚝섬", lines: ["2"], description: "" },
    { name: "마곡", lines: ["5"], description: "" },
    { name: "마곡나루", lines: ["9", "공항"], description: "환승역" },
    { name: "마두", lines: ["3"], description: "" },
    { name: "마들", lines: ["7"], description: "" },
    { name: "마산", lines: ["김포골드"], description: "" },
    { name: "마석", lines: ["경춘"], description: "" },
    { name: "마장", lines: ["5"], description: "" },
    { name: "마전", lines: ["인천2"], description: "" },
    { name: "마천", lines: ["5"], description: "" },
    { name: "마포", lines: ["5"], description: "" },
    { name: "마포구청", lines: ["6"], description: "" },
    { name: "만수", lines: ["인천2"], description: "" },
    { name: "망우", lines: ["경의중앙", "경춘"], description: "환승역" },
    { name: "망원", lines: ["6"], description: "" },
    { name: "망월사", lines: ["1"], description: "" },
    { name: "망포", lines: ["수인분당"], description: "" },
    { name: "매교", lines: ["수인분당"], description: "" },
    { name: "매봉", lines: ["3"], description: "" },
    { name: "매탄권선", lines: ["수인분당"], description: "" },
    { name: "먹골", lines: ["7"], description: "" },
    { name: "면목", lines: ["7"], description: "" },
    { name: "명동", lines: ["4"], description: "" },
    { name: "명일", lines: ["5"], description: "" },
    { name: "명지대", lines: ["용인"], description: "" },
    { name: "명학", lines: ["1"], description: "" },
    { name: "모란", lines: ["8", "수인분당"], description: "환승역" },
    { name: "모래내시장", lines: ["인천2"], description: "" },
    { name: "목동", lines: ["5"], description: "" },
    { name: "몽촌토성", lines: ["8"], description: "" },
    { name: "무악재", lines: ["3"], description: "" },
    { name: "문래", lines: ["2"], description: "" },
    { name: "문산", lines: ["경의중앙"], description: "" },
    { name: "문정", lines: ["8"], description: "" },
    { name: "문학경기장", lines: ["인천1"], description: "" },
    { name: "미금", lines: ["신분당", "수인분당"], description: "환승역" },
    { name: "미사", lines: ["5"], description: "" },
    { name: "미아", lines: ["4"], description: "" },
    { name: "미아사거리", lines: ["4"], description: "" },
    { name: "박촌", lines: ["인천1"], description: "" },
    { name: "반월", lines: ["4"], description: "" },
    { name: "반포", lines: ["7"], description: "" },
    { name: "발곡", lines: ["의정부"], description: "" },
    { name: "발산", lines: ["5"], description: "" },
    { name: "방배", lines: ["2"], description: "" },
    { name: "방이", lines: ["5"], description: "" },
    { name: "방학", lines: ["1"], description: "" },
    { name: "방화", lines: ["5"], description: "" },
    { name: "배방", lines: ["1"], description: "" },
    { name: "백마", lines: ["경의중앙", "서해"], description: "환승역" },
    { name: "백석", lines: ["3"], description: "" },
    { name: "백양리", lines: ["경춘"], description: "" },
    { name: "백운", lines: ["1"], description: "" },
    { name: "버티고개", lines: ["6"], description: "" },
    { name: "범계", lines: ["4"], description: "" },
    { name: "범골", lines: ["의정부"], description: "" },
    { name: "별내", lines: ["8", "경춘"], description: "환승역" },
    { name: "별내별가람", lines: ["4"], description: "" },
    { name: "병점", lines: ["1"], description: "" },
    { name: "보라매", lines: ["7", "신림"], description: "환승역" },
    { name: "보라매공원", lines: ["신림"], description: "" },
    { name: "보라매병원", lines: ["신림"], description: "" },
    { name: "보문", lines: ["6", "우이신설"], description: "환승역" },
    { name: "보산", lines: ["1"], description: "" },
    { name: "보정", lines: ["수인분당"], description: "" },
    { name: "보평", lines: ["용인"], description: "" },
    { name: "복정", lines: ["8", "수인분당"], description: "환승역" },
    { name: "봉명", lines: ["1"], description: "" },
    { name: "봉은사", lines: ["9"], description: "" },
    { name: "봉천", lines: ["2"], description: "" },
    { name: "봉화산", lines: ["6"], description: "" },
    { name: "부개", lines: ["1"], description: "" },
    { name: "부발", lines: ["경강"], description: "" },
    { name: "부천", lines: ["1"], description: "" },
    { name: "부천시청", lines: ["7"], description: "" },
    { name: "부천종합운동장", lines: ["7", "서해"], description: "환승역" },
    { name: "부평", lines: ["1", "인천1"], description: "환승역" },
    { name: "부평구청", lines: ["7", "인천1"], description: "환승역" },
    { name: "부평삼거리", lines: ["인천1"], description: "" },
    { name: "부평시장", lines: ["인천1"], description: "" },
    { name: "북한산보국문", lines: ["우이신설"], description: "" },
    { name: "북한산우이", lines: ["우이신설"], description: "" },
    { name: "불광", lines: ["3", "6"], description: "환승역" },
    { name: "불암산", lines: ["4"], description: "" },
    { name: "사가정", lines: ["7"], description: "" },
    { name: "사당", lines: ["2", "4"], description: "환승역" },
    { name: "사릉", lines: ["경춘"], description: "" },
    { name: "사리", lines: ["수인분당"], description: "" },
    { name: "사우", lines: ["김포골드"], description: "" },
    { name: "사평", lines: ["9"], description: "" },
    { name: "산곡", lines: ["7"], description: "" },
    { name: "산본", lines: ["4"], description: "" },
    { name: "산성", lines: ["8"], description: "" },
    { name: "삼가", lines: ["용인"], description: "" },
    { name: "삼각지", lines: ["4", "6"], description: "환승역" },
    { name: "삼동", lines: ["경강"], description: "" },
    { name: "삼산체육관", lines: ["7"], description: "" },
    { name: "삼성", lines: ["2"], description: "" },
    { name: "삼성중앙", lines: ["9"], description: "" },
    { name: "삼송", lines: ["3"], description: "" },
    { name: "삼양", lines: ["우이신설"], description: "" },
    { name: "삼양사거리", lines: ["우이신설"], description: "" },
    { name: "삼전", lines: ["9"], description: "" },
    { name: "상갈", lines: ["수인분당"], description: "" },
    { name: "상계", lines: ["4"], description: "" },
    { name: "상도", lines: ["7"], description: "" },
    { name: "상동", lines: ["7"], description: "" },
    { name: "상록수", lines: ["4"], description: "" },
    { name: "상봉", lines: ["7", "경의중앙", "경춘"], description: "환승역" },
    { name: "상수", lines: ["6"], description: "" },
    { name: "상왕십리", lines: ["2"], description: "" },
    { name: "상월곡", lines: ["6"], description: "" },
    { name: "상일동", lines: ["5"], description: "" },
    { name: "상천", lines: ["경춘"], description: "" },
    { name: "상현", lines: ["신분당"], description: "" },
    { name: "새말", lines: ["의정부"], description: "" },
    { name: "새절", lines: ["6"], description: "" },
    { name: "샛강", lines: ["9", "신림"], description: "환승역" },
    { name: "서강대", lines: ["경의중앙"], description: "" },
    { name: "서구청", lines: ["인천2"], description: "" },
    { name: "서대문", lines: ["5"], description: "" },
    { name: "서동탄", lines: ["1"], description: "" },
    { name: "서부여성회관", lines: ["인천2"], description: "" },
    { name: "서빙고", lines: ["경의중앙"], description: "" },
    { name: "서울", lines: ["GTX-A"], description: "" },
    { name: "서울대벤처타운", lines: ["신림"], description: "" },
    { name: "서울대입구", lines: ["2"], description: "" },
    { name: "서울숲", lines: ["수인분당"], description: "" },
    { name: "서울역", lines: ["1", "4", "경의중앙", "공항"], description: "환승역" },
    { name: "서울지방병무청", lines: ["신림"], description: "" },
    { name: "서원", lines: ["신림"], description: "" },
    { name: "서정리", lines: ["1"], description: "" },
    { name: "서초", lines: ["2"], description: "" },
    { name: "서현", lines: ["수인분당"], description: "" },
    { name: "석계", lines: ["1", "6"], description: "환승역" },
    { name: "석남", lines: ["7", "인천2"], description: "환승역" },
    { name: "석바위시장", lines: ["인천2"], description: "" },
    { name: "석수", lines: ["1"], description: "" },
    { name: "석천사거리", lines: ["인천2"], description: "" },
    { name: "석촌", lines: ["8", "9"], description: "환승역" },
    { name: "석촌고분", lines: ["9"], description: "" },
    { name: "선릉", lines: ["2", "수인분당"], description: "환승역" },
    { name: "선바위", lines: ["4"], description: "" },
    { name: "선부", lines: ["서해"], description: "" },
    { name: "선유도", lines: ["9"], description: "" },
    { name: "선정릉", lines: ["9", "수인분당"], description: "환승역" },
    { name: "선학", lines: ["인천1"], description: "" },
    { name: "성균관대", lines: ["1"], description: "" },
    { name: "성남", lines: ["경강", "GTX-A"], description: "환승역" },
    { name: "성복", lines: ["신분당"], description: "" },
    { name: "성수", lines: ["2"], description: "" },
    { name: "성신여대입구", lines: ["4", "우이신설"], description: "환승역" },
    { name: "성환", lines: ["1"], description: "" },
    { name: "세류", lines: ["1"], description: "" },
    { name: "세마", lines: ["1"], description: "" },
    { name: "세종대왕릉", lines: ["경강"], description: "" },
    { name: "센트럴파크", lines: ["인천1"], description: "" },
    { name: "소래포구", lines: ["수인분당"], description: "" },
    { name: "소사", lines: ["1", "서해"], description: "환승역" },
    { name: "소새울", lines: ["서해"], description: "" },
    { name: "소요산", lines: ["1"], description: "" },
    { name: "솔밭공원", lines: ["우이신설"], description: "" },
    { name: "솔샘", lines: ["우이신설"], description: "" },
    { name: "송내", lines: ["1"], description: "" },
    { name: "송도", lines: ["수인분당"], description: "" },
    { name: "송도달빛축제공원", lines: ["인천1"], description: "" },
    { name: "송산", lines: ["의정부"], description: "" },
    { name: "송정", lines: ["5"], description: "" },
    { name: "송탄", lines: ["1"], description: "" },
    { name: "송파", lines: ["8"], description: "" },
    { name: "송파나루", lines: ["9"], description: "" },
    { name: "수내", lines: ["수인분당"], description: "" },
    { name: "수락산", lines: ["7"], description: "" },
    { name: "수리산", lines: ["4"], description: "" },
    { name: "수색", lines: ["경의중앙"], description: "" },
    { name: "수서", lines: ["3", "수인분당", "GTX-A"], description: "환승역" },
    { name: "수원", lines: ["1", "수인분당"], description: "환승역" },
    { name: "수원시청", lines: ["수인분당"], description: "" },
    { name: "수유", lines: ["4"], description: "" },
    { name: "수지구청", lines: ["신분당"], description: "" },
    { name: "수진", lines: ["8"], description: "" },
    { name: "숙대입구", lines: ["4"], description: "" },
    { name: "숭실대입구", lines: ["7"], description: "" },
    { name: "숭의", lines: ["수인분당"], description: "" },
    { name: "시민공원", lines: ["인천2"], description: "" },
    { name: "시우", lines: ["서해"], description: "" },
    { name: "시청", lines: ["1", "2"], description: "환승역" },
    { name: "시청.용인대", lines: ["용인"], description: "" },
    { name: "시흥능곡", lines: ["서해"], description: "" },
    { name: "시흥대야", lines: ["서해"], description: "" },
    { name: "시흥시청", lines: ["서해"], description: "" },
    { name: "신갈", lines: ["수인분당"], description: "" },
    { name: "신검단중앙", lines: ["인천1"], description: "" },
    { name: "신금호", lines: ["5"], description: "" },
    { name: "신길", lines: ["1", "5"], description: "환승역" },
    { name: "신길온천", lines: ["4", "수인분당"], description: "환승역" },
    { name: "신내", lines: ["6", "경춘"], description: "환승역" },
    { name: "신논현", lines: ["9", "신분당"], description: "환승역" },
    { name: "신답", lines: ["2"], description: "" },
    { name: "신당", lines: ["2", "6"], description: "환승역" },
    { name: "신대방", lines: ["2"], description: "" },
    { name: "신대방삼거리", lines: ["7"], description: "" },
    { name: "신도림", lines: ["1", "2"], description: "환승역" },
    { name: "신둔도예촌", lines: ["경강"], description: "" },
    { name: "신림", lines: ["2", "신림"], description: "환승역" },
    { name: "신목동", lines: ["9"], description: "" },
    { name: "신반포", lines: ["9"], description: "" },
    { name: "신방화", lines: ["9"], description: "" },
    { name: "신사", lines: ["3", "신분당"], description: "환승역" },
    { name: "신설동", lines: ["1", "2", "우이신설"], description: "환승역" },
    { name: "신연수", lines: ["인천1"], description: "" },
    { name: "신용산", lines: ["4"], description: "" },
    { name: "신원", lines: ["경의중앙"], description: "" },
    { name: "신이문", lines: ["1"], description: "" },
    { name: "신정", lines: ["5"], description: "" },
    { name: "신정네거리", lines: ["2"], description: "" },
    { name: "신중동", lines: ["7"], description: "" },
    { name: "신창", lines: ["1"], description: "" },
    { name: "신천", lines: ["서해"], description: "" },
    { name: "신촌", lines: ["2", "경의중앙"], description: "환승역" },
    { name: "신포", lines: ["수인분당"], description: "" },
    { name: "신풍", lines: ["7"], description: "" },
    { name: "신현", lines: ["서해"], description: "" },
    { name: "신흥", lines: ["8"], description: "" },
    { name: "쌍문", lines: ["4"], description: "" },
    { name: "쌍용", lines: ["1"], description: "" },
    { name: "아라", lines: ["인천1"], description: "" },
    { name: "아산", lines: ["1"], description: "" },
    { name: "아시아드경기장", lines: ["인천2"], description: "" },
    { name: "아신", lines: ["경의중앙"], description: "" },
    { name: "아차산", lines: ["5"], description: "" },
    { name: "아현", lines: ["2"], description: "" },
    { name: "안국", lines: ["3"], description: "" },
    { name: "안산", lines: ["4", "수인분당"], description: "환승역" },
    { name: "안암", lines: ["6"], description: "" },
    { name: "안양", lines: ["1"], description: "" },
    { name: "암사", lines: ["8"], description: "" },
    { name: "암사역사공원", lines: ["8"], description: "" },
    { name: "압구정", lines: ["3"], description: "" },
    { name: "압구정로데오", lines: ["수인분당"], description: "" },
    { name: "애오개", lines: ["5"], description: "" },
    { name: "야당", lines: ["경의중앙"], description: "" },
    { name: "야목", lines: ["수인분당"], description: "" },
    { name: "야탑", lines: ["수인분당"], description: "" },
    { name: "약수", lines: ["3", "6"], description: "환승역" },
    { name: "양수", lines: ["경의중앙"], description: "" },
    { name: "양원", lines: ["경의중앙"], description: "" },
    { name: "양재", lines: ["3", "신분당"], description: "환승역" },
    { name: "양재시민의숲", lines: ["신분당"], description: "" },
    { name: "양정", lines: ["경의중앙"], description: "" },
    { name: "양주", lines: ["1"], description: "" },
    { name: "양천구청", lines: ["2"], description: "" },
    { name: "양천향교", lines: ["9"], description: "" },
    { name: "양촌", lines: ["김포골드"], description: "" },
    { name: "양평", lines: ["5", "경의중앙"], description: "환승역" },
    { name: "어룡", lines: ["의정부"], description: "" },
    { name: "어린이대공원", lines: ["7"], description: "" },
    { name: "어정", lines: ["용인"], description: "" },
    { name: "어천", lines: ["수인분당"], description: "" },
    { name: "언주", lines: ["9"], description: "" },
    { name: "여의나루", lines: ["5"], description: "" },
    { name: "여의도", lines: ["5", "9"], description: "환승역" },
    { name: "여주", lines: ["경강"], description: "" },
    { name: "역곡", lines: ["1"], description: "" },
    { name: "역삼", lines: ["2"], description: "" },
    { name: "역촌", lines: ["6"], description: "" },
    { name: "연수", lines: ["수인분당"], description: "" },
    { name: "연신내", lines: ["3", "6", "GTX-A"], description: "환승역" },
    { name: "연천", lines: ["1"], description: "" },
    { name: "염창", lines: ["9"], description: "" },
    { name: "영등포", lines: ["1"], description: "" },
    { name: "영등포구청", lines: ["2", "5"], description: "환승역" },
    { name: "영등포시장", lines: ["5"], description: "" },
    { name: "영종", lines: ["공항"], description: "" },
    { name: "영통", lines: ["수인분당"], description: "" },
    { name: "예술회관", lines: ["인천1"], description: "" },
    { name: "오금", lines: ["3", "5"], description: "환승역" },
    { name: "오남", lines: ["4"], description: "" },
    { name: "오류동", lines: ["1"], description: "" },
    { name: "오리", lines: ["수인분당"], description: "" },
    { name: "오목교", lines: ["5"], description: "" },
    { name: "오목천", lines: ["수인분당"], description: "" },
    { name: "오빈", lines: ["경의중앙"], description: "" },
    { name: "오산", lines: ["1"], description: "" },
    { name: "오산대", lines: ["1"], description: "" },
    { name: "오이도", lines: ["4", "수인분당"], description: "환승역" },
    { name: "옥수", lines: ["3", "경의중앙"], description: "환승역" },
    { name: "온수", lines: ["1", "7"], description: "환승역" },
    { name: "온양온천", lines: ["1"], description: "" },
    { name: "올림픽공원", lines: ["5", "9"], description: "환승역" },
    { name: "완정", lines: ["인천2"], description: "" },
    { name: "왕길", lines: ["인천2"], description: "" },
    { name: "왕십리", lines: ["2", "5", "경의중앙", "수인분당"], description: "환승역" },
    { name: "외대앞", lines: ["1"], description: "" },
    { name: "용답", lines: ["2"], description: "" },
    { name: "용두", lines: ["2"], description: "" },
    { name: "용마산", lines: ["7"], description: "" },
    { name: "용문", lines: ["경의중앙"], description: "" },
    { name: "용산", lines: ["1", "경의중앙"], description: "환승역" },
    { name: "용인중앙시장", lines: ["용인"], description: "" },
    { name: "우장산", lines: ["5"], description: "" },
    { name: "운길산", lines: ["경의중앙"], description: "" },
    { name: "운서", lines: ["공항"], description: "" },
    { name: "운양", lines: ["김포골드"], description: "" },
    { name: "운연", lines: ["인천2"], description: "" },
    { name: "운정", lines: ["경의중앙"], description: "" },
    { name: "운정중앙", lines: ["GTX-A"], description: "" },
    { name: "운천", lines: ["경의중앙"], description: "" },
    { name: "원당", lines: ["3"], description: "" },
    { name: "원덕", lines: ["경의중앙"], description: "" },
    { name: "원시", lines: ["서해"], description: "" },
    { name: "원인재", lines: ["수인분당", "인천1"], description: "환승역" },
    { name: "원종", lines: ["서해"], description: "" },
    { name: "원흥", lines: ["3"], description: "" },
    { name: "월계", lines: ["1"], description: "" },
    { name: "월곡", lines: ["6"], description: "" },
    { name: "월곶", lines: ["수인분당"], description: "" },
    { name: "월드컵경기장", lines: ["6"], description: "" },
    { name: "월롱", lines: ["경의중앙"], description: "" },
    { name: "을지로3가", lines: ["2", "3"], description: "환승역" },
    { name: "을지로4가", lines: ["2", "5"], description: "환승역" },
    { name: "을지로입구", lines: ["2"], description: "" },
    { name: "응봉", lines: ["경의중앙"], description: "" },
    { name: "응암", lines: ["6"], description: "" },
    { name: "의왕", lines: ["1"], description: "" },
    { name: "의정부", lines: ["1"], description: "" },
    { name: "의정부시청", lines: ["의정부"], description: "" },
    { name: "의정부중앙", lines: ["의정부"], description: "" },
    { name: "이대", lines: ["2"], description: "" },
    { name: "이매", lines: ["경강", "수인분당"], description: "환승역" },
    { name: "이수", lines: ["7"], description: "" },
    { name: "이천", lines: ["경강"], description: "" },
    { name: "이촌", lines: ["4", "경의중앙"], description: "환승역" },
    { name: "이태원", lines: ["6"], description: "" },
    { name: "인덕원", lines: ["4"], description: "" },
    { name: "인천", lines: ["1", "수인분당"], description: "환승역" },
    { name: "인천가좌", lines: ["인천2"], description: "" },
    { name: "인천공항1터미널", lines: ["공항"], description: "" },
    { name: "인천공항2터미널", lines: ["공항"], description: "" },
    { name: "인천논현", lines: ["수인분당"], description: "" },
    { name: "인천대공원", lines: ["인천2"], description: "" },
    { name: "인천대입구", lines: ["인천1"], description: "" },
    { name: "인천시청", lines: ["인천1", "인천2"], description: "환승역" },
    { name: "인천터미널", lines: ["인천1"], description: "" },
    { name: "인하대", lines: ["수인분당"], description: "" },
    { name: "일산", lines: ["경의중앙", "서해"], description: "환승역" },
    { name: "일원", lines: ["3"], description: "" },
    { name: "임진강", lines: ["경의중앙"], description: "" },
    { name: "임학", lines: ["인천1"], description: "" },
    { name: "자양", lines: ["7"], description: "" },
    { name: "작전", lines: ["인천1"], description: "" },
    { name: "잠실", lines: ["2", "8"], description: "환승역" },
    { name: "잠실나루", lines: ["2"], description: "" },
    { name: "잠실새내", lines: ["2"], description: "" },
    { name: "잠원", lines: ["3"], description: "" },
    { name: "장기", lines: ["김포골드"], description: "" },
    { name: "장승배기", lines: ["7"], description: "" },
    { name: "장암", lines: ["7"], description: "" },
    { name: "장자호수공원", lines: ["8"], description: "" },
    { name: "장지", lines: ["8"], description: "" },
    { name: "장한평", lines: ["5"], description: "" },
    { name: "전곡", lines: ["1"], description: "" },
    { name: "전대.에버랜드", lines: ["용인"], description: "" },
    { name: "정릉", lines: ["우이신설"], description: "" },
    { name: "정발산", lines: ["3"], description: "" },
    { name: "정부과천청사", lines: ["4"], description: "" },
    { name: "정왕", lines: ["4", "수인분당"], description: "환승역" },
    { name: "정자", lines: ["신분당", "수인분당"], description: "환승역" },
    { name: "제기동", lines: ["1"], description: "" },
    { name: "제물포", lines: ["1"], description: "" },
    { name: "종각", lines: ["1"], description: "" },
    { name: "종로3가", lines: ["1", "3", "5"], description: "환승역" },
    { name: "종로5가", lines: ["1"], description: "" },
    { name: "종합운동장", lines: ["2", "9"], description: "환승역" },
    { name: "주안", lines: ["1", "인천2"], description: "환승역" },
    { name: "주안국가산단", lines: ["인천2"], description: "" },
    { name: "주엽", lines: ["3"], description: "" },
    { name: "죽전", lines: ["수인분당"], description: "" },
    { name: "중계", lines: ["7"], description: "" },
    { name: "중곡", lines: ["7"], description: "" },
    { name: "중동", lines: ["1"], description: "" },
    { name: "중랑", lines: ["경의중앙", "경춘"], description: "환승역" },
    { name: "중앙", lines: ["4", "수인분당"], description: "환승역" },
    { name: "중앙보훈병원", lines: ["9"], description: "" },
    { name: "중화", lines: ["7"], description: "" },
    { name: "증미", lines: ["9"], description: "" },
    { name: "증산", lines: ["6"], description: "" },
    { name: "지석", lines: ["용인"], description: "" },
    { name: "지식정보단지", lines: ["인천1"], description: "" },
    { name: "지축", lines: ["3"], description: "" },
    { name: "지평", lines: ["경의중앙"], description: "" },
    { name: "지행", lines: ["1"], description: "" },
    { name: "직산", lines: ["1"], description: "" },
    { name: "진위", lines: ["1"], description: "" },
    { name: "진접", lines: ["4"], description: "" },
    { name: "창동", lines: ["1", "4"], description: "환승역" },
    { name: "창신", lines: ["6"], description: "" },
    { name: "천마산", lines: ["경춘"], description: "" },
    { name: "천안", lines: ["1"], description: "" },
    { name: "천왕", lines: ["7"], description: "" },
    { name: "천호", lines: ["5", "8"], description: "환승역" },
    { name: "철산", lines: ["7"], description: "" },
    { name: "청계산입구", lines: ["신분당"], description: "" },
    { name: "청구", lines: ["5", "6"], description: "환승역" },
    { name: "청담", lines: ["7"], description: "" },
    { name: "청라국제도시", lines: ["공항"], description: "" },
    { name: "청량리", lines: ["1", "경의중앙", "경춘", "수인분당"], description: "환승역" },
    { name: "청명", lines: ["수인분당"], description: "" },
    { name: "청산", lines: ["1"], description: "" },
    { name: "청평", lines: ["경춘"], description: "" },
    { name: "초당", lines: ["용인"], description: "" },
    { name: "초월", lines: ["경강"], description: "" },
    { name: "초지", lines: ["4", "수인분당", "서해"], description: "환승역" },
    { name: "총신대입구", lines: ["4"], description: "" },
    { name: "춘의", lines: ["7"], description: "" },
    { name: "춘천", lines: ["경춘"], description: "" },
    { name: "충무로", lines: ["3", "4"], description: "환승역" },
    { name: "충정로", lines: ["2", "5"], description: "환승역" },
    { name: "캠퍼스타운", lines: ["인천1"], description: "" },
    { name: "킨텍스", lines: ["GTX-A"], description: "" },
    { name: "탄현", lines: ["경의중앙"], description: "" },
    { name: "탑석", lines: ["의정부"], description: "" },
    { name: "탕정", lines: ["1"], description: "" },
    { name: "태릉입구", lines: ["6", "7"], description: "환승역" },
    { name: "태평", lines: ["수인분당"], description: "" },
    { name: "테크노파크", lines: ["인천1"], description: "" },
    { name: "퇴계원", lines: ["경춘"], description: "" },
    { name: "파주", lines: ["경의중앙"], description: "" },
    { name: "판교", lines: ["경강", "신분당"], description: "환승역" },
    { name: "팔당", lines: ["경의중앙"], description: "" },
    { name: "평내호평", lines: ["경춘"], description: "" },
    { name: "평촌", lines: ["4"], description: "" },
    { name: "평택", lines: ["1"], description: "" },
    { name: "평택지제", lines: ["1"], description: "" },
    { name: "풍무", lines: ["김포골드"], description: "" },
    { name: "풍산", lines: ["경의중앙", "서해"], description: "환승역" },
    { name: "하계", lines: ["7"], description: "" },
    { name: "하남검단산", lines: ["5"], description: "" },
    { name: "하남시청", lines: ["5"], description: "" },
    { name: "하남풍산", lines: ["5"], description: "" },
    { name: "학동", lines: ["7"], description: "" },
    { name: "학여울", lines: ["3"], description: "" },
    { name: "한강진", lines: ["6"], description: "" },
    { name: "한국항공대", lines: ["경의중앙"], description: "" },
    { name: "한남", lines: ["경의중앙"], description: "" },
    { name: "한대앞", lines: ["4", "수인분당"], description: "환승역" },
    { name: "한성대입구", lines: ["4"], description: "" },
    { name: "한성백제", lines: ["9"], description: "" },
    { name: "한양대", lines: ["2"], description: "" },
    { name: "한티", lines: ["수인분당"], description: "" },
    { name: "합정", lines: ["2", "6"], description: "환승역" },
    { name: "행당", lines: ["5"], description: "" },
    { name: "행신", lines: ["경의중앙"], description: "" },
    { name: "혜화", lines: ["4"], description: "" },
    { name: "호구포", lines: ["수인분당"], description: "" },
    { name: "홍대입구", lines: ["2", "경의중앙", "공항"], description: "환승역" },
    { name: "홍제", lines: ["3"], description: "" },
    { name: "화계", lines: ["우이신설"], description: "" },
    { name: "화곡", lines: ["5"], description: "" },
    { name: "화랑대", lines: ["6"], description: "" },
    { name: "화서", lines: ["1"], description: "" },
    { name: "화정", lines: ["3"], description: "" },
    { name: "회기", lines: ["1", "경의중앙", "경춘"], description: "환승역" },
    { name: "회룡", lines: ["1", "의정부"], description: "환승역" },
    { name: "회현", lines: ["4"], description: "" },
    { name: "효자", lines: ["의정부"], description: "" },
    { name: "효창공원앞", lines: ["6", "경의중앙"], description: "환승역" },
    { name: "흑석", lines: ["9"], description: "" },
    { name: "흥선", lines: ["의정부"], description: "" },
]
