name: subway_push
description: 내릴때 Flutter application.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  shared_preferences: ^2.5.5
  http: ^1.6.0
  flutter_local_notifications: ^21.0.0
  permission_handler: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
